name: palibert
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip=22.3.1
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - pip:
    - tqdm==4.64.1
    - datasets==2.8.0
    - transformers==4.25.1
    - tokenizers==0.13.2
    - evaluate==0.4.0
    - protobuf==3.20.3
    - mlflow==1.30.0
