$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
description: Train a Masked Language Model using HuggingFace

compute: azureml:nc6

inputs:
  # training inputs
  train_file:
    type: uri_file
    path: azureml:bpe_train_data@latest # register using data/bpe_train.yml
  model_config:
    type: uri_folder
    path: ../../../../models/palibert/
  tokenizer_config:
    type: uri_folder
    path: ../../../../models/palibert/

  # training params  
  learning_rate: 1e-4
  epochs: 5
  batch_size: 16

outputs:
  checkpoints:
    type: uri_folder

code: .

command: >-
  python ./run_mlm.py 
      --model_type roberta-base 
      --config_name ${{inputs.model_config}} 
      --tokenizer_name ${{inputs.tokenizer_config}} 
      --train_file ${{inputs.train_file}}
      --do_train 
      --num_train_epochs ${{inputs.epochs}} 
      --learning_rate ${{inputs.learning_rate}} 
      --per_gpu_train_batch_size ${{inputs.batch_size}} 
      --max_seq_length 512 
      --output_dir ${{outputs.checkpoints}} 
      --save_total_limit 2 
      --save_steps 2000 
      --seed 42 

environment: azureml:palibert@latest
